---

- hosts: all
  gather_facts: false

  tasks:

    - name: allocate azure vm
      azure_rm_virtualmachine:
        resource_group: seifertRG
        name: bp-demo-test
        allocated: yes

    - name: start azure vm
      azure_rm_virtualmachine:
        resource_group: seifertRG
        name: bp-demo-test
