---

- name: set up our server for the demo
  gather_facts: false
  hosts: all
  tasks:

    - name: install python3
      dnf: 
        name: python3
        state: present

    - name: install nodejs
      dnf:
        name: nodejs
        state: present

    - name: create /site
      file:
        path: /site
        state: directory
        mode: '0755'

    - name: copy package to /site
      copy:
        src: ~/packagewhatpackage
        dest: /site

        
