---

- name: set up our server for the demo
  gather_facts: false
  hosts: node-2
  tasks:

    - name: install python3
      dnf: 
        name: python3
        state: present

    - name: install nodejs
      dnf:
        name: nodejs
        state: present

    - name: create /site
      file:
        path: /site
        state: directory
        mode: '0755'

    - name: copy package to /site
      copy:
        src: ~/packagewhatpackage
        dest: /site

    - name: create symlink for npm service
      file:
        src: /site/packagewhatpackage/npmSite.service
        dest: /etc/systemd/system/
        state: link

        