---
#renmove the base for our demo

- name: clean up our server
  gather_facts: false
  hosts: all
  tasks:

    - name: remove python3
      dnf: 
        name: python3
        state: absent

    - name: remove httpd
      dnf: 
        name: httpd
        state: absent

    - name: remove nodejs
      dnf:
        name: nodejs
        state: absent

    - name: remove the directory for the app
      file:
        path: /site/packagewhatpackage
        state: absent
