---

- hosts: all
  gather_facts: false

  tasks:

   - name: turn off firewall to make sure things are ok
     shell: systemctl stop firewalld.service

   - name: set enforce to 0
     shell: setenforce 0

#   - name: start the npm service so the site works
#     shell: npm start
#     args:
#       chdir: /site/packagewhatpackage/
#     poll: 5
