---

- hosts: all
  gather_facts: false

  tasks:

   - name: create link to npm service
     file:
       src: /etc/systemd/system
       dest: ~/packagewhatpackage/npmSite.service
       state: link

   - name: restart systemd daemon
     shell: systemctl daemon-reload

   - name: start npm
     shell: systemctl start npmSite.service
