---

- hosts: all
  gather_facts: false

  tasks:

    - name: run my python script
      shell: python3 batAuctions.py
      args: 
        chdir: ~/py-scripts
      remote_src: yes

    - name: validate file was created
      find:
        path: ~/py-scripts
        age: 10s
        recurse: yes
        patterns: '*-data.json'
      remote_src: yes
      register: jsonData

    - name: move file to correct location
      file:
        src: jsonData
        dest: /site/packagewhatpackage/
        mode: '0755'
        remote_src: yes